#use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'UGCKit_Example' do
  pod 'UGCKit', :path => '../'

  target 'UGCKit_Tests' do
    inherit! :search_paths

    
  end
end
